/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalhoformais;

import java.awt.Component;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabriel Patatt
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNaoTerminal = new javax.swing.JTextField();
        txtTerminal = new javax.swing.JTextField();
        txtProd = new javax.swing.JTextField();
        btnGerar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtSimboloInicial = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtConjuntoProd = new javax.swing.JTextField();
        txtProd2 = new javax.swing.JTextField();
        txtProd3 = new javax.swing.JTextField();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Não terminais:");

        jLabel3.setText("Terminais:");

        jLabel4.setText("Produções:");

        txtNaoTerminal.setText("s,a");
        txtNaoTerminal.setToolTipText("");

        txtTerminal.setText("a,b,c");

        txtProd.setText("S=aA;bB");

        btnGerar.setText("Gerar");
        btnGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarActionPerformed(evt);
            }
        });

        jLabel5.setText("Símbolo inicial:");

        txtSimboloInicial.setText("S");

        jLabel6.setText("Conjunto de Produção: ");

        txtConjuntoProd.setText("P");

        txtProd2.setText("B=a");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(btnGerar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtProd3, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addComponent(txtProd2)
                    .addComponent(txtNaoTerminal, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addComponent(txtProd, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addComponent(txtConjuntoProd)
                    .addComponent(txtTerminal, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addComponent(txtSimboloInicial))
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNaoTerminal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTerminal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtConjuntoProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSimboloInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtProd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtProd3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(btnGerar)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarActionPerformed
        Resultado r = new Resultado();
        
        String[] producao = txtProd.getText().split("[;=]");
        String[] producao2 = txtProd2.getText().split("[;=]");
        String[] producao3 = txtProd3.getText().split("[;=]");
        
       
       
        
        if(txtNaoTerminal.getText().isEmpty() ){//testa se há não terminais para gerar a gramática
            JOptionPane.showMessageDialog (null, "Não é possível gerar gramática com os não-terminais vazios!");//exibe a mensagem na tela
            System.exit(WIDTH);
        }
        else if (txtProd.getText().isEmpty() || txtProd2.getText().isEmpty() || txtProd3.getText().isEmpty())
            JOptionPane.showMessageDialog (null, "Favor preencher no mínimo 3 produções! Exemplo de expressão aceita : S=aA;bB;");//exibe a mensagem na tela
        
        else if(txtTerminal.getText().isEmpty()){
            r.Recebe(txtNaoTerminal.getText().toUpperCase(), "$", producao, txtSimboloInicial.getText().toUpperCase(), txtConjuntoProd.getText().toUpperCase(), producao2, producao3,txtProd.getText());// Caso a caixa de texto "terminais" esteja em branco, entende-se que o usuário quis dizer como vazia.                                                                           // passando assim para gramática o símbolo que adotamos : "$", representando o vazio.
            r.setVisible(true);
        }
        else if(!txtProd.getText().contains("=") || !txtProd.getText().contains(";")){
            JOptionPane.showMessageDialog (null, "Exemplo de expressão aceita : S=aA;bB; !");
        }
        else{
               r.Recebe(txtNaoTerminal.getText().toUpperCase(), txtTerminal.getText(), producao, txtSimboloInicial.getText().toUpperCase(),  txtConjuntoProd.getText().toUpperCase(), producao2, producao3, txtProd.getText());
               r.setVisible(true);
        }
        
        
     
    }//GEN-LAST:event_btnGerarActionPerformed


    
    public void main(String args[]) {
       
       
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtConjuntoProd;
    private javax.swing.JTextField txtNaoTerminal;
    private javax.swing.JTextField txtProd;
    private javax.swing.JTextField txtProd2;
    private javax.swing.JTextField txtProd3;
    private javax.swing.JTextField txtSimboloInicial;
    private javax.swing.JTextField txtTerminal;
    // End of variables declaration//GEN-END:variables
}
